### ISSUE TITLE
Bug in section name comparison (".data" || ".rodata") - GolangStaticStringRecovery.java

### ISSUE THREAD

**Issue by xmpf** [advanced-threat-research/GhidraScripts#1]
https://github.com/advanced-threat-research/GhidraScripts/blob/83a7924bd12e2b94b0a74023010e357a4780ebae/GolangStaticStringRecovery.java#LL63C6-L63C6

Original:

```java
if (block.getName().equalsIgnoreCase(".data") == false
&& block.getName().equalsIgnoreCase(".rodata") == false) {
continue;
}
```

Should be:

```java
if (block.getName().equalsIgnoreCase(".data") == false
|| block.getName().equalsIgnoreCase(".rodata") == false) {
continue;
}
```

**Comment by ThisIsLibra** [comment]
Thank you for reporting the bug! https://github.com/advanced-threat-research/GhidraScripts/commit/e9074d0e42cda6e6c6458b3c63873356f7bb1eee should resolve the issue as I've now updated it.

**Comment by ThisIsLibra** [comment]
I erroneously merged this request, since the comparison should be done with "&&" rather than "||". The condition should only be true if neither of the names are matching the given names. When using "||", failure to meet the first part of the condition will always lead to skip the section, even if its name is equal to the second.

**Comment by ThisIsLibra** [comment]
With the recent commit [1c4c243](https://github.com/advanced-threat-research/GhidraScripts/commit/1c4c243d7f1a617f6fd9f0a9669e51eec59a7eff), this has now been reverted
